
FROM huggingface/transformers-pytorch-cpu

ENV LANG=C.UTF-8

RUN mkdir /python

ENV PYTHONPATH=/python

RUN pip3 install sentencepiece protobuf fastapi uvicorn pydantic prometheus_client

COPY download.py .

RUN python3 download.py

